[package]
name = "jwt_authentication_rust_warp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.196", features = ["derive"]}
tokio = {version = "1.36.0", features = ["full"]}
warp =  "0.3.6"
